name: 游 Deploy NestJS Blog Backend API to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Actualizado a v4 (buena pr치ctica)

    - name: Copy project to VPS
      uses: appleboy/scp-action@v0.1.7 # Actualizado a v0.1.7 (crucial)
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        source: "."
        target: "/post-api"
        debug: true # Esto te ayudar치 a ver m치s info si falla

    - name: Run deploy commands on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd /post-api
          
          # Manejo de errores m치s seguro para matar el proceso
          echo "Matar proceso en el puerto 3000..."
          # Si no hay proceso, esto no fallar치 gracias al "|| true"
          sudo lsof -t -i:3000 | xargs -r sudo kill -9 || true
          
          echo -e "${{ secrets.ENV_FILE }}" > .env
          
          npm install
          npm run build
          
          # Reinicio seguro de PM2
          pm2 reload nestjs-blog-backend-api || pm2 start dist/main.js --name nestjs-blog-backend-api
          pm2 save